### ISSUE TITLE
NoClassDefFoundError Exception

### ISSUE THREAD

**Issue by jcady** [rtyley/spongycastle#19]
My application uses Spongy Castle 1.54.0.0 loaded through Maven in Android Studio (I include core, prov, pkix, and pg).

It works fine on my main development devices.  I recently tried testing on an older device (Galaxy S3 4.4.2 [API 19]) and I get a this fatal exception whenever the application is loaded.

The exception occurs when loading the library using this in the main application file:

```
static
{
    Security.insertProviderAt(new org.spongycastle.jce.provider.BouncyCastleProvider(), 1);
}
```

Here's the full stack trace starting after that call:

```
java.lang.NoClassDefFoundError: org.spongycastle.util.Arrays
            at org.spongycastle.asn1.ASN1ObjectIdentifier$OidHandle.<init>(ASN1ObjectIdentifier.java:449)
            at org.spongycastle.asn1.ASN1ObjectIdentifier.intern(ASN1ObjectIdentifier.java:425)
            at org.spongycastle.asn1.pkcs.PKCSObjectIdentifiers.<clinit>(PKCSObjectIdentifiers.java:117)
            at org.spongycastle.jcajce.provider.digest.MD2$Mappings.configure(MD2.java:70)
            at org.spongycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(BouncyCastleProvider.java:220)
            at org.spongycastle.jce.provider.BouncyCastleProvider.setup(BouncyCastleProvider.java:135)
            at org.spongycastle.jce.provider.BouncyCastleProvider.access$000(BouncyCastleProvider.java:44)
            at org.spongycastle.jce.provider.BouncyCastleProvider$1.run(BouncyCastleProvider.java:127)
            at java.security.AccessController.doPrivileged(AccessController.java:45)
            at org.spongycastle.jce.provider.BouncyCastleProvider.<init>(BouncyCastleProvider.java:123)
```

Any idea what's going on?  It looks like some dependency might be missing, but those should be taken care of through Maven.

**Comment by rtyley** [comment]
Sounds like a proguard problem?

**Comment by jcady** [comment]
I thought that initially too, but this is a debug build that isn't using proguard.

I figured it out today. The problem was that my application is using multidex because it has over 64K references.  It looks like some of the spongycastle references weren't being put in the main dex file, but they were trying to be accessed through the static method (which I had in my main application file) before they could be loaded through multidex, which caused the crash.  The crash only occurred on pre-5.0 because 5.0 changed how dex files are processed, it allowed for pre-compiling multiple dex files at install time of APKs.  Pre-5.0 has to rely on doing it at runtime using Dalvik, hence why trying to use any reference that isn't in the main dex file on pre-5.0 before giving a chance for the multidex library to load them will cause a crash.

The solution for me was to simply move the static method to my crypto helper file where I actually do the calls that use spongycastle.  This delays the call until after the application has loaded all the dex files.

Not strictly related to spongycastle, but I'll leave this here in case someone else encounters the same issue.

**Comment by Giszmo** [comment]
Ran into this, too. I think it is a spongy issue as spongy advertises to put this static block "somewhere" and spongy is made for use with Android, so it's kind of obvious people will run into this. Maybe it would be worth mentioning to put this anywhere where it runs after multidex loading aka not into Application constructor or static block. Looks like Application.onCreate is fine.

https://developer.android.com/studio/build/multidex.html#mdex-gradle
