### ISSUE TITLE
There are some problems in using Oracle JDK1.8 encryption and decryption, so it does not support it?

### ISSUE THREAD

**Issue by shenjianhua1985** [rtyley/spongycastle#44]
hi，
 when I useing oracle JDK1.8，get error:

java.lang.SecurityException: JCE cannot authenticate the provider SC
	at javax.crypto.Cipher.getInstance(Cipher.java:656)
	at com.test.ecc.EckeySCTest.publicEncrypt(EckeySCTest.java:56)
	at com.test.ecc.EckeySCTest.test(EckeySCTest.java:71)
	at com.test.ecc.EckeySCTest.main(EckeySCTest.java:48)
Caused by: java.util.jar.JarException: file:/D:/blockchain/repository/com/madgag/spongycastle/prov/1.58.0.0/prov-1.58.0.0.jar has unsigned entries - org/spongycastle/jce/MultiCertStoreParameters.class

**Comment by iddo** [comment]
I'm affected by this issue, was a solution found?
